apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "conductor.fullname" . }}
  labels:
    {{- include "conductor.labels" . | nindent 4 }}
data:
  HARNESS.md: |-
    {{- .Values.harness | nindent 4 }}
